# Popis: Makefile pro testovaci programy
# Autor: Martin Zelinka, xzelin12@stud.fit.vutbr.cz

all:
	make -C dir
	make -C memory
	make -C open
	make -C write
	make -C net/client
	make -C net/server

clean:
	make clean -C dir
	make clean -C memory
	make clean -C open
	make clean -C write
	make clean -C net/client
	make clean -C net/server
